# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0002_auto_20170619_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='project',
            name='Project_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
